//==================================================
//     Outputs that match the input variables
//==================================================
output "command_unix" {
  description = "The value of the `command_unix` input variable, or the default value if the input was `null`."
  value       = local.command_unix
}
output "command_windows" {
  description = "The value of the `command_windows` input variable, or the default value if the input was `null`."
  value       = local.command_windows
}

//==================================================
//       Outputs generated by this module
//==================================================
output "command" {
  description = "The command that was tested (either the `command_unix` or `command_windows` input variable, depending on which system this configuration is being run on)."
  value       = local.command
}
output "exists" {
  description = "Whether the given command exists."
  value       = local.exists
}
